### ISSUE TITLE
Task 4.2.2.2: SR Source

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#112]
- [ ] Usage example
- [ ] Data format documentation
- [ ] Produce data (Source intensity distribution)
- [ ] Deposit data incl. DOI generation

**Comment by richardbriggs** [comment]
From the example OASYS workflow I have, the SR source seems fairly easy to implement. The number of rays, seed, undulator energy and delta energy are all set at the undulator module; also with the machine parameters : (size, divergence, undulator length).
![undulator](https://user-images.githubusercontent.com/20657974/27635651-25af5178-5c08-11e7-8e7f-5694f0c418ce.png)

**Comment by CFGrote** [comment]
Are you going to make a usage showcase for this? If not, I can do it. Same question for the propagation in Oasys ( #115 ).
