### ISSUE TITLE
Task 4.2.2.8: PMI - shock compression

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#118]
- [x] Usage example
- [x] Data format documentation
- [x] Produce data (rad-hydro dump)
- [x] Deposit data incl. DOI generation

**Comment by richardbriggs** [comment]
https://doi.org/10.5281/zenodo.883106 for input files and output files of a 50 µm CH + 5 µm Fe experiment, with 6 ns flat top laser at 0.3 TW/cm**2
