### ISSUE TITLE
Task 4.2.2.10: Signal from optically thick sample

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#121]
SAXS image from overdense plasma
- [x] Usage example
- [x] Data format documentation
- [x] Produce data (SAXS images)
- [x] Deposit data incl. DOI generation

XAFS signal from shock compressed warm dense matter
- [x] Usage example
- [ ] Data format documentation
- [x] Produce data (XAFS spectrum)
- [ ] Deposit data incl. DOI generation

**Comment by richardbriggs** [comment]
This is done in essence for the X-ray absorption side. EXAFS modelling of a simple Fe foil has been carried out and we have demonstrated simulations of XANES at shock conditions in Raffa Torchio's 2016 paper [Scientific Reports 7(1) 26402 (2016)]. It will need some discussion on how best to incorporate the whole XANES/EXAFS simulation programs (beyond FEFF) into SIMEX.

**Comment by CFGrote** [comment]
@n01r , @bussmann 
hi guys, anything happening here? we're three weeks from the deadline and i would like to avoid a situation like  last time...

a short updated would be nice.

thanks

**Comment by n01r** [comment]
I am extremely sorry for the delay! The simulations have been run - we're finalizing the report right now.
