### ISSUE TITLE
Missing histogram in SimEx Tutorial, Diffraction

### ISSUE THREAD

**Issue by JPBGoe** [PaNOSC-ViNYL/SimEx#123]
In the wiki 'SimEx Tutorial', in section 'Diffraction', in subsection 'Analyzing the results':

If
   $> diffr_diagnostics.py -S "range(1,11)" -P  ./diffr/<filename>.h5
is executed, no histogram is shown. Instead there is another image of the diffraction pattern.

**Comment by CFGrote** [comment]
Fixed by commit 2db078c38
