### ISSUE TITLE
Tutorial nano crystal diffraction geometry Parameter not set

### ISSUE THREAD

**Issue by belfhi** [PaNOSC-ViNYL/SimEx#159]
CrystFELPhotonDiffractorParameters does not set geometry in constructor.

**Comment by n01r** [comment]
```python
parameters = CrystFELPhotonDiffractorParameters(
     ...
    detector_geometry='simple.geom',    # External file that contains the detector geometry in CrystFEL notation.
    )
```
Apparently the tutorial was wrong because it used the keyword `geometry` but the class constructor requires `detector_geometry`. Strangely we got not error from using an unknown keyword.
