### ISSUE TITLE
Approval

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#169]
EUCALL WP4 (SIMEX) Milestone M4.4
Tested and documented simulation code

The simulation software is tested, documented, and approved by WP Partners.

**Comment by bussmann** [comment]
Approved and happy about it!

**Comment by belfhi** [comment]
Approved!

**Comment by sharma35** [comment]
Approved!
Congratulations!!!

**Comment by ax3l** [comment]
Well done, approved!

**Comment by CFGrote** [comment]
Yes, fine with me.

Thanks for all.

Sakura

**Comment by CFGrote** [comment]
Yes, approved!
With regards,
Ashutosh

Get Outlook for Android<https://aka.ms/ghei36>




On Fri, Sep 28, 2018 at 12:42 PM +0200, "Carsten Fortmann-Grote" <carsten.grote@xfel.eu<mailto:carsten.grote@xfel.eu>> wrote:


Dear all,
i need at least (Mathias or Sakura) and (Ashutosh or Alexander) to
approve Milestone M4.4 for SIMEX.

Please reply to this email and just say "Yes" or "Approved". That's all.

Many thanks, Carsten

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer
wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax:   +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Nicole Elleuche

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165


________________________________

A jelen email útján megküldött vélemény vagy információ kizárólag a küldő személyéhez kapcsolódik és nem feltétlenül jeleníti meg az ELI-HU Nonprofit Kft. álláspontját is. Társaságunk nem vállal felelősséget az email tartalmáért, ide értve különösen, de nem kizárólagosan kötelezettségvállalást jogi kötő erővel bíró szerződések létrehozásáért, módosításáért vagy megszűntetéséért, valamint az átadott információ alapján indult eljárásokért mindaddig, amíg az adott információt utólag és írásban a megfelelően meghatalmazott vagy az ELI-HU Nonprofit Kft. képviseleti jogával felruházott személy meg nem erősíti. Az email bizalmas vagy jogilag védett információt tartalmazhat, amelyet kizárólag a címzett személy vagy szervezet, illetve az általuk felhatalmazottak használhatnak fel. Amennyiben Ön nem az üzenet címzettje, kérjük, értesítse erről az üzenet küldőjét és törölje az üzenetet rendszeréből. A jelen email tartalmának nem a címzett általi bármilyen formában történő illetéktelen közzététele, terjesztése, másolása, illetve felhasználása vagy alkalmazása szigorúan tilos és jogszabályba ütközhet.


Please note that any information or opinions presented in this email are solely those of the sender and do not necessarily represent those of ELI-HU Nonprofit Ltd. Our Company accepts no liability or responsibility for the content of this email, especially, but not limited to commitment for establishing, modifying or terminating legally binding contracts, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing by a person duly authorized or endowed with the right of representation of ELI-HU Nonprofit Ltd. This email may contain confidential or legally protected information, and is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. If you are not the intended recipient of this email, please inform the sender immediately and delete it from your system. Any unauthorized disclosure, dissemination, copying or use of or reliance upon the content of this email by anyone other than the intended recipient is strictly prohibited and may be unlawful.

**Comment by CFGrote** [comment]
All approved, closing.
