### ISSUE TITLE
Diffraction of infinite lattice/large scale crystal

### ISSUE THREAD

**Issue by rshopa** [PaNOSC-ViNYL/SimEx#176]
My question might be out of scope yet of high importance for the comparison x ray diffraction on nano- and large-scale objects. In [Deliverable D4.5 report](https://www.eucall.eu/sites/sites_custom/site_eucall/content/e21597/e25317/e79593/EUCALL_WP4_SIMEX_Deliverable_4_5_D28_30_09_2018.pdf?preview=preview), there's a discussion on _singFEL_ and _CrystFEL_ outcomes for the case of nano-scaled Fe2O3 crystals if compared to obtained by simulation package _mercury_, but for the ideal infinite lattice (Figure 2 and Figure 3).
I wonder whether it is possible to perform such simulation for a large periodic structure using SimEx. 

Going further, is it even possible to extend the range of experiments within the framework to, say, non-linear phenomena, e.g. multi-photon excitation, parametric down-conversion or second harmonic generation? Such effects might require models for laser-plasma interactions. 

The key problem here might be the limitation for _Xraypac_ (demo-only _XMDYN_, as far as I see), hence it is impossible to include the impact of intense x rays on core electrons (which is essential since photon energies are above the electron binding energies). I guess _Xraypack_ is indeed capable to model such phenomena.

**Comment by CFGrote** [comment]
hi roman, 

----- Original Message -----

**Comment by rshopa** [comment]
Thank you, Carsten.
I will consider the eventual model for the simulation using Xraypac.
