### ISSUE TITLE
Refactor IO

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#19]
Each special calculator has more or less the same logic for setting up the number and type of output files depending on the type and number of input files. Can this be generalized and moved to either the AbstractPhoton\* or even the AbstractBaseCalculator?

**Comment by bussmann** [comment]
Dear Carsten, these and others are important design considerations that might limit the scalability of the simex_platform severely. We should talk VERY soon.

Best, Michael

**Comment by CFGrote** [comment]
Hi Micha,
yes, we should. I was thinking about having a new teleconference
beginning next week, are you available?

carsten

## 

Carsten Fortmann-Grote
Scientist
European XFEL GmbH

Mail: carsten.grote@xfel.eu
Phone: +49 (0)40 8998 5603

**Comment by bussmann** [comment]
Should be

Am 10.02.2016 um 09:45 schrieb Carsten Fortmann-Grote:

**Comment by CFGrote** [comment]
- Each file must contain the parameters pertaining to the simulation and the history of previous simulation steps.
- Support default filenames
