### ISSUE TITLE
Build without MKL

### ISSUE THREAD

**Issue by buzmakov** [PaNOSC-ViNYL/SimEx#32]
I'll try to install simex_platform locally in empty container on ubuntu 14.04.

1) The list of all necessary packages for build  simex_platform the following:

```
apt-get update && apt-get install -y wget python2.7 python-numpy python-scipy python-h5py python-setuptools python-matplotlib build-essential libbz2-dev libgsl0-dev libfftw3-dev liblapack-dev cmake unzip 
```

(unzip not mentioned in Readme. )

2) I'm fail to build  simex_platform, because I have not Intel MKL library installed locally.
Is it any way to build recon using lapack if MKL absent?

```
Building recon.
if [ -d  ]; then \
                cd /home/simex_platform/build/../build/externals/src/recon/s2e_recon/DM_Src && \
                make mkl;\
        fi
make[1]: Entering directory `/home/simex_platform/build/externals/src/recon/s2e_recon/DM_Src'
gcc -O3 object_recon.c -o object_recon -m64 -I/include -I/include/fftw -Wl,--no-as-needed -L/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lpthread -lm
object_recon.c: In function 'setup':
object_recon.c:260:8: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
  fscanf(fp, "%d %d", &qmax, &num_supp) ;
        ^
object_recon.c:272:19: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
             fscanf(fp, "%d", &supp[s][i]) ;
                   ^
object_recon.c:354:11: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
     fscanf(fp, "%lf", &intens) ;
           ^
object_recon.c:403:10: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
    fscanf(fp, "%lf", &x[i][j][k]) ;
          ^
/usr/bin/ld: cannot find -lmkl_intel_lp64
/usr/bin/ld: cannot find -lmkl_core
/usr/bin/ld: cannot find -lmkl_sequential
collect2: error: ld returned 1 exit status
make[1]: *** [mkl] Error 1
make[1]: Leaving directory `/home/simex_platform/build/externals/src/recon/s2e_recon/DM_Src'
make: *** [/home/simex_platform/build/../build/externals/src/recon/build_dm.stamp] Error 2
root@e68cf649b3ea:/home/simex_platform/build# exit
```

**Comment by bussmann** [comment]
Dear all, this is important. We should avoid vendor-specific dependencies BUT always be able to use that version of a function that is optimum for a given hardware.

This currently is neither possible with all BLAS/LAPACK flavours nor with FFTs. For FFTs we at HZDR have written a common C++ interface based on template metaprogramming that allows for optimized FFTs using a single interface which we could provide within SIMEX.

I strongly suggest to check existing simex_platform code for these obstacles and go for a 'single source yet optimum' approach to stay hardware independent yet fast. Python should help here but without a full code audit I feel unable to point out all possible traps.

The CI should at least test on various hardware platforms.

**Comment by SergeyYakubov** [comment]
Hi!

If you try a new version from Master branch that uses CMake, the program should compile without mkl, providing you have fftw and other stuff installed. It should also give you warnings if something is missed.

**Comment by CFGrote** [comment]
hi sergey,
sounds great. however, i don't see a relevant commit in master (did you
forget to push?)

for new_hierarchy, i would like to move Sources/unittest to
Sources/python/unittest and Sources/python/SimEx to
Sources/python/src/SimEx, to keep the symmetry and to have the same
structure for other languages.

regards,

## 

Carsten Fortmann-Grote
Scientist
European XFEL GmbH

Mail: carsten.grote@xfel.eu
Phone: +49 (0)40 8998 5603

**Comment by bussmann** [comment]
Thanks. I can't check but it would be EXTREMELY useful to have optimized versions for Intel, AMD, NVIDIA Hardware and corresponding cmake flags.

**Comment by SergeyYakubov** [comment]
There is a problem that SimEx is using modules provided by the partners. These modules use some 3rd-party libraries that should be preinstalled on the system.

So, the steps to use optimized version would be:
1. Install necessary optimized software (intel MKL, cuda, etc)
2. Compile 3rd party libraries that are needed by modules (armadillo, boost, fftw, ...)
3. During modules compilation we can try to use these optimized versions. With some modules it will work (those that use CMake, actually only singfel at the moment). Another module, for example, downloads and installs fftw by itself.

We already discussed it with Carsten. We don't want to go into the module code/Makefile and change it by ourself. Ideally, there should be some standard (predefined CMake variables) that all modules would use during installation - which compiler to use, which version of library, etc. If all of the partners use it, we can then have a singe top CMake where all settings could be done.

So, partially, there is already an option to use optimized libraries, but it is not completely working, because not all of the modules knows about it.

**Comment by bussmann** [comment]
Dear Sergey,

I understand your point and like your suggestion alot. We use cmake so no problem here.

This should be discussed with the other partners, then.

Best, Michael

**Comment by CFGrote** [comment]
hi,

On 03/21/2016 04:07 PM, SergeyYakubov wrote:

> There is a problem that SimEx is using modules provided by partners.
> These modules use some 3rd-party libraries that should be preinstalled
> on the system.
> 
> So, the steps to use optimized version would be:
> 1. Install necessary optimized software (intel MKL, cuda, etc)
> 2. Compile 3rd party libraries that are needed by modules (armadillo,
>    boost, fftw, ...)
> 3. During modules compilation we can try to use these optimized
>    versions. With some modules it will work (those that use CMake,
>    actually only singfel at the moment). Another module, for example,
>    downloads and installs fftw by itself.
> 
> We already discussed it with Carsten. We don't want to go into the
> module code/Makefile and change it by ourself. Ideally, there should be
> some standard (predefined CMake variables) that all modules would use
> during installation - which compiler to use, which version of library,
> etc. If all of the partners use it, we can then have a singe top CMake
> where all settings could be done.
> Yes, on the other hand, we are patching 3rd part sources and makefiles
> already, I would not worry about patching e.g. the wpg makefile such
> that it does not pull fftw but uses the system wide (but beware, only
> fftw2 works afaik.)

carsten

**Comment by bussmann** [comment]
As long as I'm not involved in maintaining this, I'm fine with this ; -)

**Comment by SergeyYakubov** [comment]
I agree that  patching is not the best solution. Someone can change something and we may have problems. For singfel we are already replacing the whole CMakeLists file, which is not good at all. 

While we don't have general solution, we can do it manually and step by step. Now MKL works, no MKL works. Then we can make CUDA work, then openblas, and so on, depending on the requests. And I believe that MKL will be installed everywhere, where performance plays a role (cluster, etc.) On a local machine it will be slow anyway:).

**Comment by buzmakov** [comment]
Hi,
Now all builds successful.
On ubuntu 14.04 the list of dependencies is: 

apt-get install -y wget python2.7 python-numpy python-scipy python-h5py python-setuptools python-matplotlib build-essential libbz2-dev libgsl0-dev libfftw3-dev liblapack-dev libhdf5-dev libopenmpi-dev cmake libarmadillo-dev libboost1.55-all-dev unzip cython

**Comment by CFGrote** [comment]
@buzmakov, @SergeyYakubov 
can we close this one?

**Comment by SergeyYakubov** [comment]
yes
