### ISSUE TITLE
Interface orientation module

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#4]
Write a calculator that interfaces the EMC orientational reconstruction algorithm.

**Comment by bussmann** [comment]
As for the phasing module (https://github.com/eucall-software/simex_platform/issues/5), please clarify what an orientation module is supposed do and reference a publication on the EMC orientational reconstruction algorithm.

**Comment by CFGrote** [comment]
Loh & Elser, PRE _80_ 026705 (2009)
