### ISSUE TITLE
Documentation of Calculators

### ISSUE THREAD

**Issue by ax3l** [PaNOSC-ViNYL/SimEx#40]
(This issue documents offline results from last weeks discussions between @CFGrote and @ax3l. @CFGrote can you please edit to correct wrong and add missing information? :) )
## Beamline Elements

Currently, `calculators` act as the algorithmic building blocks describing subsequent stages in the beamline. The [following calculators](https://github.com/eucall-software/simex_platform/blob/6994737ab2060e378bccf916327ac35c7b63ce1c/Tests/python/unittest/SimExTest/PhotonExperimentSimulation/PhotonExperimentSimulationTest.py#L90-L96) are currently known, all prefixed with `photon_`:
- _source_:
  - description: representation of the light source (e.g. as a wavefront, rays, photon distribution) at the very beginning of the photon experiment, i.e. before any optics or photon matter interaction has happened.
  - example: The code FAST generates 3D (x-y-t) wavefronts at the exit of the undulator in an x-ray free electron laser.
- _propagator_:
  - description: Propagates the light from the light source through a sequence of optical elements (lenses, mirrors, gratings, apertures ,...) to the sample/target interaction point.
  - example: Propagation of wavefronts by means of Fourier wave optics. E.g. implemented in [WPG](https://github.com/samoylv/WPG)
- _interactor_:
  - description: Interaction of the photons with the target or sample. Takes into account elementary processes like absorption, emission, scattering of radiation and secondary processes like collisional ionization and recombination. The end product is the electronic state of the sample/target as a function of time during the interaction with the external light source.
  - example: particle-in-cell simulations, radiation-hydrodynamics simulations, molecular dynamics, and many more ...
- _diffractor_:
  - description: multiplication of form-factors with incoming field & propagation to ideal detector
  - example: Scattering of x-ray pulses from a molecule or a plasma
- _detector_:
  - description: adds electric response of detector: multi-photon, Compton, boundary effects, ...
  - example: 
- _analyzer_:
  - description: currently only relevant for single-particle images: calculates the 3D electron density in the sample by solving the inverse scattering problem (scattering-signal -> density) through orientation of 2D diffraction patterns and iterative phasing.  
  - example: Expand-Maximize-Compress (EMC) for orientation, Difference-Map for phasing.
### Code Coupling
- `source` and `propagation` can be modeled in the wave-front approximation via [SRW](https://github.com/ochubar/SRW) with it's Python Binding and high-level interface [WPG](https://github.com/samoylv/WPG). A complementary method is raytracing, e.g. using the
  code [Shadow](https://github.com/srio/shadow3), python bindings via [xrt](https://github.com/kklmn/xrt) or [oasys](https://github.com/srio/oasys-installation-scripts)
- A short-pulse laser-plasma experiment would be modeled with [PIConGPU](http://picongpu.hzdr.de/) and replaces both `interactor` and `diffractor`. The X-FEL beam can be discretized into the photon picture from its wavefront description, see scripts in #37.
- An ideal detector result from PIConGPU (2D openPMD "images") can be fed back into the `detector` calculator.
### Related Questions
- #7
- #8
- #31

**Comment by CFGrote** [comment]
on my list ...

this is a very good starting point for the document to be written in
fulfillment of deliverable 4.1 .

On 05/23/2016 10:20 AM, Axel Huebl wrote:

> Assigned #40
> https://github.com/eucall-software/simex_platform/issues/40 to
> @CFGrote https://github.com/CFGrote.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/eucall-software/simex_platform/issues/40#event-668620606

## 

## 

Carsten Fortmann-Grote
Scientist
European XFEL GmbH

Mail: carsten.grote@xfel.eu
Phone: +49 (0)40 8998 5603

**Comment by ax3l** [comment]
great! I edited the description on GitHub a bit further from my minutes. Feel free to edit those! :)

**Comment by CFGrote** [comment]
Transferred to [new repo](https://github.com/eucall-software/simex_docs)
