### ISSUE TITLE
Fix errors observed on travis

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#42]
The errors reported from travisCI (see e.g. this log: https://travis-ci.org/eucall-software/simex_platform/jobs/132826264) are not reproduced if build+test on local machine. It seems that some test files are not installed correctly in the build on travisCI, see debug print in lines 3635ff. Someone with more experience with travisCI (@ax3l ?) might be quicker to solve this.

Thanks, Carsten

**Comment by ax3l** [comment]
looks like we [forgot to close a file after we opened it](http://stackoverflow.com/questions/26613570/hdf5-file-created-with-h5py-cant-be-opened-by-h5py/26730843#26730843).

What `h5py` is [saying in this line](https://travis-ci.org/eucall-software/simex_platform/jobs/132826264#L3650) `IOError: Unable to open file (Unable to find a valid file signature)` is: the file I shall open is not a valid HDF5 file, e.g., because `close()` was not yet called and it is not (yet) a valid file with all its meta.

**Comment by ax3l** [comment]
Actually the file in `Tests/python/unittest/TestFiles/pmi_out_0000001.h5` looks damaged.

When I am trying to open it locally, via

``` python
import h5py as h5

f = h5.File("Tests/python/unittest/TestFiles/pmi_out_0000001.h5", "r")
# crash!

print(h5.__version__)
# 2.5.0

h5.version?
# This is h5py **2.5.0**
# 
# * HDF5 version: **1.8.13**
2.5.0
```

I am also getting the  `Unable to open file (File signature not found)` error.
(Note: travis used HDF5 1.8.13 atm and also the latest `h5py` release.)

My version of `HDFview` can not open this file either :)

**Comment by CFGrote** [comment]
hm strange. no such error here...
ipython session:

In[3]: h5=h5py.File('pmi_out_0000001.h5', 'r')

In [4]: print h5py.**version**
2.2.1

In [5]: h5py.version?
Type:       module
String Form:<module 'h5py.version' from '/usr/lib/python2.7/dist-packages/h5py/version.pyc'>
File:       /usr/lib/python2.7/dist-packages/h5py/version.py
Docstring:
This is h5py **2.2.1**
- HDF5 version: **1.8.11**

On 05/25/2016 02:38 PM, Axel Huebl wrote:

> Actuall the file in |Tests/python/unittest/TestFiles/pmi_out_0000001.h5|
> looks damaged.
> 
> When I am trying to open it locally, via
> 
> import h5py as h5
> 
> f = h5.File("Tests/python/unittest/TestFiles/pmi_out_0000001.h5", "r")
> 
> # crash!
> 
> print(h5.**version**)
> 
> # 2.5.0
> 
> h5.version?
> 
> # This is h5py **2.5.0**
> 
> #
> 
> # \* HDF5 version: **1.8.13**
> 
> 2.5.0
> 
> I am also getting the |Unable to open file (File signature not found)|
> error.
> (Note: travis used HDF5 1.8.13 atm and also the latest |h5py| release.)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/eucall-software/simex_platform/issues/42#issuecomment-221562362

## 

## 

Carsten Fortmann-Grote
Scientist
European XFEL GmbH

Mail: carsten.grote@xfel.eu
Phone: +49 (0)40 8998 5603

**Comment by ax3l** [comment]
Ah of course, we need to run a `git lfs pull` in travis, now! :D Will update!

**Comment by CFGrote** [comment]
i was just beginning to smell sth like this ;) glad you found out.

**Comment by CFGrote** [comment]
Fixed. So the crucial commits are 
485c264530570d86614152a69f67fd9b6575634b (git pull lfs)
eaa1a378278d3de63cb57d5797ddae4334d7cf6d (git install lfs)
51a994d6ddb1f6fef29e418641cbab7e14876a48 (remove pylab)
