### ISSUE TITLE
Interface phasing module

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#5]
Interface the difference map phasing algorithm

**Comment by CFGrote** [comment]
Write a calculator for the DM phasing algorithm

**Comment by bussmann** [comment]
As we are working in a multi-disciplinary environment it would be good to elaborate a bit on what you mean by "phasing module" in order to clarify what such a module does and what function it has in the workflow. Also, please reference a publication if you talk about a certain algorithm.

**Comment by CFGrote** [comment]
the phasing module that is currently in simS2E and that i'm planning to
incorporate into simex_platform is based on the Difference-Map algorithm
as described here:
Elser et al Proc. Natl. Acad. Sci. USA _104_, 418 (2007)
also referenced and summarized here:
Loh & Elser, PRE _80_ 026705 (2009) which is the reference for the
orientation reconstruction algorithm (EMC) currently in simS2E and
planned for simex_platform.

carsten
