### ISSUE TITLE
Fix singfel build

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#54]
Currently, singfel sources are downloaded from a db link, this sucks. better would be to download from repo git@bitbucket.org:chunhongyoon/singfel.git (@chuckie82 's original) or git@bitbucket.org:racnets/singfel.git (my fork).
all patches from singfel's CMakeLists.txt should be applied upstream and removed from our build system.

**Comment by CFGrote** [comment]
use singfel in the eucall-software repo

**Comment by CFGrote** [comment]
always run Tests/python/functest/SimExTest/Backengines/singfel/singfelTest.py to check if old code results are reproduced

**Comment by SergeyYakubov** [comment]
done (except last comment)
