### ISSUE TITLE
Interface Esther Rad-Hydro

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#62]
Make Calculator and data interface for the 1D Rad-hydro code Esther using RB's input file generator.

**Comment by richardbriggs** [comment]
Can this be closed now that we have the EstherExperimentConstruction calculator?

**Comment by CFGrote** [comment]
i guess so, yes.

carsten

On Mon, Sep 18, 2017 at 11:24:18AM +0000, Richard Briggs wrote:
> Can this be closed now that we have the EstherExperimentConstruction calculator?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/eucall-software/simex_platform/issues/62#issuecomment-330191995

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax:   +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165
