### ISSUE TITLE
Download FEFF8.5L(ite) and add to build system as external dependency

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#67]
Here's the link: http://leonardo.phys.washington.edu/feff/Bin-Source-feff8Lite/Source/feff85L.f
- [x] Add to eucall-software
- [x] Add cmake to feff 
- [x] build in simex_platform using cmake, support MKL, use ifort, if present.. there's a typo in the code, has to be fixed.

**Comment by SergeyYakubov** [comment]
1. Better would be to put it to simex_software github and download it during installation.
2. Link to MKL, ifort? What if there is no MKL and ifort?

**Comment by CFGrote** [comment]
ok for 1., if no intel, then use gfortran, of course

**Comment by CFGrote** [comment]
@SergeyYakubov, can you review 7273b41c ?

thanks.

**Comment by SergeyYakubov** [comment]
Yes.

Can you open me write access to feff8.5light

**Comment by SergeyYakubov** [comment]
done.
