### ISSUE TITLE
Adjust SingFELPhotonDiffractor

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#71]
The singFEL backengine now produces one hdf5 file per mpi process. Some adjustments in the python frontend might be neccessary.

**Comment by CFGrote** [comment]
Needed one fix in singfel (a110169b73bc338b791b2371302601d2fc8d1a49) and one test fix.

**Comment by CFGrote** [comment]
ready for review

**Comment by SergeyYakubov** [comment]
looks ok
