### ISSUE TITLE
Installing simex_platform .deb on ubuntu14.04, boost dependency

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#91]
this one was reported by  a user:

 % sudo dpkg --install simex-0.2.0-Ubuntu16.04.deb
Selecting previously unselected package simex.
(Reading database ... 396984 files and directories currently installed.)
Preparing to unpack simex-0.2.0-Ubuntu16.04.deb ...
Unpacking simex (0.2.0) ...
dpkg: dependency problems prevent configuration of simex:
 simex depends on libboost-all-dev (>= 1.55); however:
  Package libboost-all-dev is not installed.

dpkg: error processing package simex (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 simex

Although this seems like a pretty clear problem, I actually went to the trouble of installing libboost1.55-all-dev specifically and apt-get seems to agree with me:

 % sudo apt-get install libboost1.55-all-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost1.55-all-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

I've tried different versions of libboost but I get the same dependency issues, would you know of a work around? Once again, don't stress about replying while you're on holiday, I have other things I can do until you get back.

**Comment by robnagler** [comment]
FWIW, 

```
# dpkg --install simex-0.2.0-Ubuntu16.04.deb
Selecting previously unselected package simex.
(Reading database ... 111700 files and directories currently installed.)
Preparing to unpack simex-0.2.0-Ubuntu16.04.deb ...
Unpacking simex (0.2.0) ...
Setting up simex (0.2.0) ...
Requirement already satisfied: periodictable in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: pyparsing in /usr/lib/python2.7/dist-packages (from periodictable)
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from periodictable)
# apt show libboost-all-dev
Package: libboost-all-dev
Version: 1.58.0.1ubuntu1
Priority: optional
Section: universe/libdevel
Source: boost-defaults
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Boost Team <pkg-boost-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 10.2 kB
Depends: libboost-dev, libboost-tools-dev, libboost-atomic-dev, libboost-chrono-dev, libboost-context-dev, libboost-coroutine-dev, libboost-date-time-dev, libboost-exception-dev, libboost-filesystem-dev, libboost-graph-dev, libboost-graph-parallel-dev, libboost-iostreams-dev, libboost-locale-dev, libboost-log-dev, libboost-math-dev, libboost-mpi-dev, libboost-mpi-python-dev, libboost-program-options-dev, libboost-python-dev, libboost-random-dev, libboost-regex-dev, libboost-serialization-dev, libboost-signals-dev, libboost-system-dev, libboost-test-dev, libboost-thread-dev, libboost-timer-dev, libboost-wave-dev
Homepage: http://www.boost.org/
Download-Size: 2,228 B
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Description: Boost C++ Libraries development files (ALL) (default version)
 The Boost web site provides free, peer-reviewed, portable C++ source
 libraries. The emphasis is on libraries which work well with the C++
 Standard Library. One goal is to establish "existing practice" and
 provide reference implementations so that the Boost libraries are
 suitable for eventual standardization. Some of the libraries have
 already been proposed for inclusion in the C++ Standards Committee's
 upcoming C++ Standard Library Technical Report.
 .
 This metapackage provides the complete Boost development environment,
 including all separately-packaged libraries.
 .
 This package is a dependency package, which depends on Debian's default
 Boost version (currently 1.58).
# Linux xenial 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Vagrant box: kurron/xenial-server-docker     (virtualbox, 5.1.12)

**Comment by SergeyYakubov** [comment]
It is not a bug. Simex debian package is for version 16.04, not for 14.04. The problem is that the standard boost package for 14.04 is too old, so the dependency cannot be satisfied. What we can do:
1. Nothing. Recommend user to update Ubuntu, or install simex manually, or use Docker.
2. Create a package for 14.04 without boost. Boost should be then installed manually and be found-able by SimEx.
3. Create and include correct boost package to simex deb file.
4. Get rid of boost in singfel. It is basically used to read command line arguments and wrap MPI commands. Could do that as well without it.

I would opt for solution 1 or 4. 4) requires more work :).

**Comment by SergeyYakubov** [comment]
ok, there seems to be a standard libboost1.55-all-dev in ubuntu 14.04. So in 3) we would not need to create a package ourselves, just change dependency to libboost1.55-all-dev.

But I'm still not sure if we should support the old(er) Ubuntu version.
